// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	avsicli "github.com/0xPellNetwork/pelldvs/avsi/client"
	mock "github.com/stretchr/testify/mock"
)

// ClientCreator is an autogenerated mock type for the ClientCreator type
type ClientCreator struct {
	mock.Mock
}

// NewAVSIClient provides a mock function with no fields
func (_m *ClientCreator) NewAVSIClient() (avsicli.Client, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewAVSIClient")
	}

	var r0 avsicli.Client
	var r1 error
	if rf, ok := ret.Get(0).(func() (avsicli.Client, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() avsicli.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(avsicli.Client)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClientCreator creates a new instance of ClientCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientCreator {
	mock := &ClientCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
