name: Docker Publish E2E Hardhat

on:
  workflow_dispatch:
    inputs:
      contract_version:
        description: 'Contracts version (example: v0.2.32)'
        required: true

jobs:
  build_and_publish:
    name: Build
    runs-on: [  "Linux", "X64", "ci" ]
    environment: e2e-docker
    permissions:
      packages: write
      contents: read
    env:
      DFT_CONTRACT_VERSION: v0.2.32
      IMAGE_NAME: pellnetwork/pelldvs-e2e-hardhat

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set CONTRACT_VERSION env
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "CONTRACT_VERSION=${{ github.event.inputs.contract_version }}" >> $GITHUB_ENV
          else
            echo "CONTRACT_VERSION=${{ env.DFT_CONTRACT_VERSION }}" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./test/e2e
          file: ./test/e2e/docker/contracts/Dockerfile
          push: true
          build-args: |
            CONTRACT_VERSION=${{ env.CONTRACT_VERSION }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.CONTRACT_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            github_token=${{ secrets.GH_TOKEN }}
