# Verify that important design docs have ToC entries.
name: Check documentation ToC
on:
  pull_request:
    push:
      branches:
        - main
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
