name: e2e
# Runs the CI end-to-end test network on all pushes to v0.38.x
# and every pull request, but only if any Go files have been changed.
on:
  workflow_dispatch: # allow running workflow manually
  pull_request:
  push:
    branches:
      - dev
jobs:
  e2e-test:
    runs-on: [ "self-hosted", "Linux", "X64", "ci" ]
    timeout-minutes: 40
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      TAG: ${{ github.event.pull_request.head.sha || github.workflow_sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Stop services first
        working-directory: test/e2e
        run: make docker-down
        if: always()
      - name: Build docker images
        working-directory: test/e2e
        run: make docker-build-all
      - name: Stop services
        working-directory: test/e2e
        run: docker compose down --volumes
      - name: Start services
        working-directory: test/e2e
        run: docker compose up operator -d --remove-orphans
      - name: sleep 60 seconds for services to start
        working-directory: test/e2e
        run: sleep 60
      - name: Test services
        working-directory: test/e2e
        run: make docker-test-pelle2e
        env:
          TIMEOUT_FOR_TASK_PROCESS: 60
      - name: Stop services for cleanup
        working-directory: test/e2e
        run: make docker-down
        if: always()
