name: Goimports Lint
on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ dev ]

jobs:
  generate-check:
    name: Verify
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: false

      - name: Install tools
        run: |
          go install github.com/incu6us/goimports-reviser/v3@latest

      - name: Setup private repo
        run: git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/0xPellNetwork".insteadOf "https://github.com/0xPellNetwork"

      - name: Format imports
        run: make lint-imports

      - name: Verify goimports
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Error: Goimports are not up to date."
            echo "Please run 'make lint-imports' locally and commit the changes."
            git status
            git diff
            exit 1
          fi
