name: Test
on:
  pull_request:
  push:
    paths:
      - "**.go"
    branches:
      - dev
jobs:
  tests:
    runs-on: [ "self-hosted", "Linux", "X64", "ci" ]
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        part: [ "00", "01", "02", "03", "04", "05" ]
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      TAG: ${{ github.event.pull_request.head.sha || github.workflow_sha }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: false
      - uses: actions/checkout@v4
      - name: private
        run: git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/0xPellNetwork".insteadOf "https://github.com/0xPellNetwork"
      - name: Run Go Tests
        run: |
          make test-group-${{ matrix.part }} NUM_SPLIT=6
